### ISSUE TITLE
1.20.6 Support?

### ISSUE THREAD

**Issue by Raidware** [ploppyperson/RealFish#2]
Add new mc version support if possiblr

**Comment by ploppyperson** [comment]
does anything not work?

**Comment by Raidware** [comment]
> does anything not work?

i havent tested.

**Comment by ploppyperson** [comment]
There isn't any reason why it shouldn't? If there are issues though do report them.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
